//frontend/scripts/injectEnv.js
require('dotenv').config();
const fs = require('fs');

const env = {
    REACT_APP_CLAUD_PROFILE: process.env.REACT_APP_CLAUD_PROFILE,
    REACT_APP_RECAPTCHA_SITE_KEY: process.env.REACT_APP_RECAPTCHA_SITE_KEY,
    REACT_APP_STRIPE_PUBLIC_KEY: process.env.REACT_APP_STRIPE_PUBLIC_KEY,
    REACT_APP_BACKEND_URL: process.env.REACT_APP_BACKEND_URL,
    REACT_APP_PLACE_HOLDER_IMG: process.env.REACT_APP_PLACE_HOLDER_IMG,
    REACT_APP_CLAUD_PROFILE_IMG: process.env.REACT_APP_CLAUD_PROFILE_IMG,
    REACT_APP_ELO_IMAGE_URL: process.env.REACT_APP_ELO_IMAGE_URL,
    REACT_APP_ELO_COIN_IMAGE_URL: process.env.REACT_APP_ELO_COIN_IMAGE_URL,
    REACT_APP_ELO_EVENT_IMAGE_URL: process.env.REACT_APP_ELO_EVENT_IMAGE_URL,
    REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
    REACT_APP_FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
    REACT_APP_FIREBASE_DATABASE_URL: process.env.REACT_APP_FIREBASE_DATABASE_URL,
    REACT_APP_FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
    REACT_APP_FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
    REACT_APP_FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
    PORT: process.env.PORT
  // Adicione outras variáveis de ambiente aqui
};

fs.writeFileSync('./.env.firebase.json', JSON.stringify(env));
